[build]
  command = "NODE_OPTIONS='--max_old_space_size=4096' yarn run build"
  publish = "build"
  base = ""

[context.production.environment]
  NODE_ENV = "production"
  NPM_CONFIG_UNSAFE_PERM = "true"
  CI = "true"

[[plugins]]
  package = "@netlify/plugin-cache"

  [plugins.inputs]
  paths = ["node_modules/**", "build/**"]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
